In [52]:
import emoji

In [53]:
print( type( emoji.UNICODE_EMOJI ) )

<class 'dict'>


In [54]:
print( emoji.emojize( ":angry_face:" ) )

print( emoji.emojize( ":OK_hand_light_skin_tone:" ) )

😠
👌🏻


In [55]:
import pandas as pd

In [56]:
data = pd.read_csv( "train_emoji.csv", header = None )

In [57]:
data.head( n = 10 )

0  1   2     3
0              never talk to me again  3 NaN   NaN
1     I am proud of your achievements  2 NaN   NaN
2      It is the worst day in my life  3 NaN   NaN
3                    Miss you so much  0 NaN   [0]
4                        food is life  4 NaN   NaN
5                      I love you mum  0 NaN   NaN
6                Stop saying bullshit  3 NaN   NaN
7  congratulations on your acceptance  2 NaN   NaN
8         The assignment is too long   3 NaN   NaN
9                   I want to go play  1 NaN   [3]

In [58]:
emoji_dict = {
    
    0 : ":beating_heart:",
    1 :":baseball:",
    2 :":beaming_face_with_smiling_eyes:",
    3 :":disappointed_face:",
    4 :":fork_and_knife:"
    
}

In [59]:
for ix in emoji_dict.values():
    
    print( emoji.emojize( ix ) )

💓
⚾
😁
😞
🍴


In [60]:
X_train = data[0]

Y_train = data[1]

In [61]:
m,  = X_train.shape

m

132

In [62]:
Y_train.shape

(132,)

In [63]:
print( X_train[0] )

never talk to me again


In [64]:
print( emoji.emojize( emoji_dict[Y_train[0]] ) )

😞


In [65]:
import warnings

warnings.filterwarnings( "ignore" )

In [66]:
# convert every sentence into a list of words

for ix in range( 132 ) :
    
    X_train[ix] = X_train[ix].lower().split()

In [67]:
print( X_train[0] )

['never', 'talk', 'to', 'me', 'again']


In [68]:
def read_glove_vecs( glove_file ) :
    
    with open( glove_file, 'r', encoding='utf8' ) as f :
        
        words = set()
        
        word_to_vec_map = {}
        
        for line in f :
            
            line = line.strip().split()
            
            curr_word = line[0]
            
            words.add( curr_word )
            
            word_to_vec_map[curr_word] = np.array( line[1:], dtype = np.float64 )
        
        i = 1
        
        words_to_index = {}
        
        index_to_words = {}
        
        for w in sorted( words ) :
            
            words_to_index[w] = i
            
            index_to_words[i] = w
            
            i = i + 1
            
    return words_to_index, index_to_words, word_to_vec_map

In [72]:
import numpy as np

words_to_index, index_to_words, word_to_vec_map = read_glove_vecs( "glove.6B.50d.txt" )

In [73]:
word_to_vec_map["happy"]

array([ 0.092086,  0.2571  , -0.58693 , -0.37029 ,  1.0828  , -0.55466 ,
       -0.78142 ,  0.58696 , -0.58714 ,  0.46318 , -0.11267 ,  0.2606  ,
       -0.26928 , -0.072466,  1.247   ,  0.30571 ,  0.56731 ,  0.30509 ,
       -0.050312, -0.64443 , -0.54513 ,  0.86429 ,  0.20914 ,  0.56334 ,
        1.1228  , -1.0516  , -0.78105 ,  0.29656 ,  0.7261  , -0.61392 ,
        2.4225  ,  1.0142  , -0.17753 ,  0.4147  , -0.12966 , -0.47064 ,
        0.3807  ,  0.16309 , -0.323   , -0.77899 , -0.42473 , -0.30826 ,
       -0.42242 ,  0.055069,  0.38267 ,  0.037415, -0.4302  , -0.39442 ,
        0.10511 ,  0.87286 ])

In [74]:
word_to_vec_map["happy"].shape

(50,)

In [75]:
def avg_vector( words ) :
    
    ans = word_to_vec_map[words[0]]
    
    for i in range( 1, len( words ) ) :
        
        ans = np.add( ans, word_to_vec_map[words[i]] )
        
    ans = ans/float( len( words ) )
    
    return ans    

In [76]:
ans = avg_vector( X_train[0] )

In [77]:
ans

array([ 9.718460e-02,  1.743740e-02,  5.284300e-02, -4.368060e-01,
        2.756132e-01, -1.426688e-01, -6.120520e-01,  4.716140e-01,
       -6.059740e-01,  1.566594e-01, -8.662400e-02,  4.906620e-01,
       -6.480320e-01, -1.612960e-01,  8.897200e-01,  4.867520e-01,
        4.601260e-02, -8.363342e-02, -2.288840e-01, -4.151500e-01,
       -1.140000e-02,  6.407600e-01,  5.954280e-01,  1.780868e-01,
        7.128668e-01, -2.072760e+00, -3.161338e-01,  1.869920e-01,
        6.583040e-01, -6.969300e-01,  3.172380e+00,  5.411100e-01,
       -5.941440e-01, -3.028740e-01, -2.285386e-01, -2.899120e-01,
        2.006040e-01,  1.053064e-01, -3.933000e-02, -4.483020e-01,
       -1.353596e-01, -2.031200e-03, -2.454976e-01,  1.305460e-01,
       -1.976000e-02,  2.025340e-02, -1.199070e-01, -2.522034e-01,
       -2.197784e-01,  3.076060e-01])

In [78]:
X_numbers = np.zeros( ( 132, 50 ) )

In [79]:
for i in range( X_train.shape[0] ):
    
    X_numbers[i] = avg_vector( X_train[i] )

In [98]:
print( X_numbers.shape )

X_numbers

(132, 50)


array([[ 0.0971846 ,  0.0174374 ,  0.052843  , ..., -0.2522034 ,
        -0.2197784 ,  0.307606  ],
       [ 0.00563117,  0.59711333, -0.13939717, ..., -0.06701233,
        -0.025773  ,  0.32180167],
       [ 0.27343125,  0.33763875, -0.33053875, ..., -0.335001  ,
         0.06524875, -0.04257963],
       ...,
       [ 0.29220562,  0.1533622 , -0.015246  , ...,  0.032272  ,
         0.1313342 ,  0.472114  ],
       [-0.00701397,  0.54196333, -0.19225433, ..., -0.80106333,
        -0.20057967,  0.78087   ],
       [-0.1149985 ,  0.6452325 , -0.39727   , ...,  0.142175  ,
        -0.2057708 ,  0.5231    ]])

In [99]:
from keras.models import Sequential

from keras.layers import Dense, Input,Activation

from keras.utils import to_categorical

In [100]:
model = Sequential()

In [101]:
# Build neural network

model.add( Dense( 10, activation = 'relu', input_shape= ( 50, ) ) )

model.add( Dense( 5, activation = 'softmax' ) )

In [102]:
model.compile( optimizer = 'adam',
              
              loss = 'categorical_crossentropy',
              
              metrics = ['accuracy'] )

In [103]:
print( Y_train.shape )

Y_onehot = to_categorical( Y_train )

print( Y_onehot.shape )

(132,)
(132, 5)


In [104]:
print( Y_train[0] )

print( Y_onehot[0] )

3
[0. 0. 0. 1. 0.]


In [105]:
model.fit( X_numbers, Y_onehot, epochs = 100 )

Epoch 1/100
132/132 [==============================] - 0s 466us/step - loss: 1.6969 - accuracy: 0.1364
Epoch 2/100
132/132 [==============================] - 0s 65us/step - loss: 1.6792 - accuracy: 0.1515
Epoch 3/100
132/132 [==============================] - 0s 78us/step - loss: 1.6649 - accuracy: 0.1894
Epoch 4/100
132/132 [==============================] - 0s 93us/step - loss: 1.6521 - accuracy: 0.2197
Epoch 5/100
132/132 [==============================] - 0s 76us/step - loss: 1.6418 - accuracy: 0.2273
Epoch 6/100
132/132 [==============================] - 0s 75us/step - loss: 1.6291 - accuracy: 0.2500
Epoch 7/100
132/132 [==============================] - 0s 89us/step - loss: 1.6205 - accuracy: 0.2652
Epoch 8/100
132/132 [==============================] - 0s 69us/step - loss: 1.6115 - accuracy: 0.2727
Epoch 9/100
132/132 [==============================] - 0s 92us/step - loss: 1.6026 - accuracy: 0.2727
Epoch 10/100
132/132 [==============================] - 0s 61us/step - loss: 1.59

132/132 [==============================] - 0s 53us/step - loss: 1.0644 - accuracy: 0.6136
Epoch 81/100
132/132 [==============================] - 0s 76us/step - loss: 1.0582 - accuracy: 0.6136
Epoch 82/100
132/132 [==============================] - 0s 95us/step - loss: 1.0531 - accuracy: 0.6288
Epoch 83/100
132/132 [==============================] - 0s 67us/step - loss: 1.0471 - accuracy: 0.6439
Epoch 84/100
132/132 [==============================] - 0s 73us/step - loss: 1.0418 - accuracy: 0.6667
Epoch 85/100
132/132 [==============================] - 0s 102us/step - loss: 1.0359 - accuracy: 0.6591
Epoch 86/100
132/132 [==============================] - 0s 72us/step - loss: 1.0307 - accuracy: 0.6591
Epoch 87/100
132/132 [==============================] - 0s 51us/step - loss: 1.0269 - accuracy: 0.6667
Epoch 88/100
132/132 [==============================] - 0s 69us/step - loss: 1.0227 - accuracy: 0.6742
Epoch 89/100
132/132 [==============================] - 0s 62us/step - loss: 1.0167 -

In [106]:
print( data[0][7] )

['congratulations', 'on', 'your', 'acceptance']


In [109]:
output = np.argmax( model.predict( X_numbers ), axis = 1 )

In [110]:
print( Y_train[:10] )

0    3
1    2
2    3
3    0
4    4
5    0
6    3
7    2
8    3
9    1
Name: 1, dtype: int64


In [111]:
np.sum( output == Y_train )

90

In [113]:
text = "i love this movie"

avg_v = avg_vector( text.split() )

print( avg_v.shape )

avg_v = avg_v.reshape( 1, 50 )

print( avg_v )

(50,)
[[ 0.2047575   0.4665125  -0.39385825 -0.21400375  0.5693875   0.19566
  -0.327045   -0.2054374  -0.4126725   0.65301189 -0.3267025   0.653345
  -0.642835    0.0626755   1.1503925   0.0891825   0.2911375   0.3365475
  -0.33327625 -0.2663675  -0.027435    0.65283     0.4776025   0.38726075
   0.9074375  -1.81335    -1.2968875   0.21994     0.696095   -0.74308275
   3.187125    0.273342   -0.18172    -0.1216975  -0.20048825 -0.0903625
   0.1265975   0.01179    -0.1867775  -0.607775   -0.12607333  0.258237
  -0.2903175  -0.08328534 -0.193961    0.18942425  0.069061   -0.6600925
  -0.18246     0.6113375 ]]


In [114]:
emoji_label_predict = np.argmax( model.predict( avg_v ) )

In [115]:
print( emoji_label_predict )

print( emoji.emojize( emoji_dict[emoji_label_predict] ) )

2
😁
